Build the front-end

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+    # Add parameter here
     steps:
       - run:
           name: Destroy environments
@@ -16,7 +16,7 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+    # Add parameter here
     steps:
       - run:
           name: Revert migrations
@@ -31,7 +31,7 @@ commands:
             #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -39,14 +39,15 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [ frontend-build ]
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            cd frontend
+            npm install
+            npm run build
       - save_cache:
-          paths: [frontend/node_modules]
+          paths: [ frontend/node_modules ]
           key: frontend-build
 
   build-backend:
@@ -55,51 +56,51 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [ backend-build ]
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            # Your code here
+            exit 1
       - save_cache:
-          paths: [backend/node_modules]
+          paths: [ backend/node_modules ]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+    # Docker image here
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-                
+    # Checkout code from git
+    # Restore from cache
+    # Your job code here
+
   test-backend:
     docker:
-      # Docker image here
+    # Docker image here
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-            
+    # Checkout code from git
+    # Restore from cache
+    # Your job code here
+
   scan-frontend:
     docker:
-      # Docker image here
+    # Docker image here
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+    # Checkout code from git
+    # Restore from cache
+    # Your job code here
 
   scan-backend:
     docker:
-      # Docker image here
+    # Docker image here
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+    # Checkout code from git
+    # Restore from cache
+    # Your job code here
 
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
+    # Docker image here that supports AWS CLI
     steps:
       # Checkout code from git
       - run:
@@ -133,7 +134,7 @@ jobs:
 
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
+    # Docker image here that supports Ansible
     steps:
       # Checkout code from git
       # Add ssh keys with fingerprint
@@ -152,7 +153,7 @@ jobs:
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
+    # Docker image here that supports NodeJS
     steps:
       # Checkout code from git
       - run:
@@ -165,11 +166,11 @@ jobs:
           command: |
             # Your code here
             exit 1
-     # Here's where you will add some code to rollback on failure      
+      # Here's where you will add some code to rollback on failure
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
+    # Docker image here that supports AWS CLI
     steps:
       # Checkout code from git
       - run:
@@ -186,11 +187,11 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure      
-                    
+            # Here's where you will add some code to rollback on failure      
+
   deploy-backend:
     docker:
-      # Docker image here that supports Ansible
+    # Docker image here that supports Ansible
     steps:
       # Checkout code from git
       # Add ssh keys with fingerprint
@@ -207,7 +208,7 @@ jobs:
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
+    # Lightweight Docker image
     steps:
       # Checkout code from git
       - run:
@@ -230,7 +231,7 @@ jobs:
 
   cloudfront-update:
     docker:
-      # Docker image here that supports AWS CLI
+    # Docker image here that supports AWS CLI
     steps:
       # Checkout code from git
       - run:
@@ -244,24 +245,24 @@ jobs:
       # Here's where you will add some code to rollback on failure  
 
 cleanup:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
+  docker:
+  # Docker image here
+  steps:
+    # Checkout code from git
+    - run:
+        name: Get old stack workflow id
+        command: |
+          # your code here
+          export OldWorkflowID="the id here"
+          export STACKS=[] #put the list of stacks here
+    - run:
+        name: Remove old stacks and files
+        command: |
+          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+          then
             # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              # your code here
-            fi
-            
+          fi
+
 
 workflows:
   default:
@@ -269,29 +270,29 @@ workflows:
       - build-frontend
       - build-backend
       - test-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - test-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          requires: [ test-frontend, test-backend, scan-frontend, scan-backend ]
           filters:
             branches:
-              only: [test-feature-branch]
+              only: [ test-feature-branch ]
       - configure-infrastructure:
-          requires: [deploy-infrastructure]
+          requires: [ deploy-infrastructure ]
       - run-migrations:
-          requires: [configure-infrastructure]
+          requires: [ configure-infrastructure ]
       - deploy-frontend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - deploy-backend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+          requires: [ deploy-backend, deploy-frontend ]
       - cloudfront-update:
-          requires: [smoke-test]
+          requires: [ smoke-test ]
       - cleanup:
-          requires: [cloudfront-update]
+          requires: [ cloudfront-update ]
